<a href="https://colab.research.google.com/github/Phuc1Le/pyTorch-from-scratch/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
import numpy as np

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [4]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [6]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [7]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [8]:
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [9]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [13]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [11]:
tensor_c = tensor_b.reshape(4,-1)
tensor_c

tensor([[5],
        [6],
        [7],
        [8]])

In [16]:
tensor_a*tensor_c

tensor([[30, 40, 50, 60],
        [36, 48, 60, 72],
        [42, 56, 70, 84],
        [48, 64, 80, 96]])

In [14]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [15]:
tensor_a

tensor([ 6,  8, 10, 12])