<a href="https://colab.research.google.com/github/Phuc1Le/pyTorch-from-scratch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [8]:
my_list = [[1,2,3,4,5], [6,7]]
my_list

[[1, 2, 3, 4, 5], [6, 7]]

In [10]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.8865,  0.0353, -0.3194, -1.3933],
        [ 1.7681,  0.5116, -0.8661,  1.5125],
        [ 1.3984,  2.0721,  0.2488, -1.8326]])

In [11]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
np1 = np.random.randn(3,4)
np1

array([[-0.51445231, -0.28256714,  1.84044399,  0.02332003],
       [ 1.34667215,  1.27895216, -0.11599928,  0.91123926],
       [ 0.4565426 ,  0.40401389, -0.64251167, -0.28350106]])

In [13]:
tensor1 = torch.tensor(np1)
tensor1

tensor([[-0.5145, -0.2826,  1.8404,  0.0233],
        [ 1.3467,  1.2790, -0.1160,  0.9112],
        [ 0.4565,  0.4040, -0.6425, -0.2835]], dtype=torch.float64)