<a href="https://colab.research.google.com/github/Phuc1Le/pyTorch-from-scratch/blob/main/Tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_tensor = torch.arange(10)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_tensor.reshape(2,5)
my_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
my_tensor.reshape(5,-1)
my_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
my_tensor.view(10,1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [11]:
my_tensor.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
from math import nan
my_torch_2 = torch.tensor([1,2,nan,4,5,6,7,8,9,10])
mt3 = my_torch_2.view(2,5)
mt3

tensor([[ 1.,  2., nan,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [21]:
my_torch_2[0] = 11
mt3

tensor([[11.,  2., nan,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [34]:
tens = torch.arange(10)

In [42]:
tens= tens.reshape(5,-1)
print(tens)
tens[:, 1:]

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


tensor([[1],
        [3],
        [5],
        [7],
        [9]])